/**
 * Re-exports shared copilot schemas for use in API routes.
 */
export {
  copilotAnswerBodySchema,
  copilotAnswerResponseSchema,
  copilotCitationSchema,
  copilotCreateSessionBodySchema,
  copilotFallbackReasonSchema,
  copilotFeedbackBodySchema,
  copilotFeedbackResponseSchema,
  copilotFeedbackVoteSchema,
  copilotMessageRoleSchema,
  copilotMessageSchema,
  copilotPinBodySchema,
  copilotRunStatsSchema,
  copilotSessionDetailSchema,
  copilotSessionIdSchema,
  copilotSessionSummarySchema,
  copilotSessionsListResponseSchema,
  copilotSessionsQuerySchema,
  copilotVisitorIdSchema,
  type CopilotAnswerBody,
  type CopilotAnswerResponse,
  type CopilotCitation,
  type CopilotFeedbackVote,
  type CopilotFallbackReason,
  type CopilotMessage,
  type CopilotRunStats,
  type CopilotSessionDetail,
  type CopilotSessionSummary,
} from '@sg/shared/schemas/copilot';
