#!/bin/bash

# 简化版远程部署脚本（手动步骤）

SERVER_IP="47.96.3.44"
SERVER_USER="root"

echo "📋 手动部署步骤："
echo ""
echo "1. 在本地打包项目："
echo "   cd /Users/zengdan/startup-graveyard"
echo "   tar --exclude='.git' --exclude='node_modules' --exclude='.next' -czf startup-graveyard.tar.gz ."
echo ""
echo "2. 上传到服务器："
echo "   scp startup-graveyard.tar.gz root@$SERVER_IP:/tmp/"
echo ""
echo "3. SSH连接到服务器："
echo "   ssh root@$SERVER_IP"
echo ""
echo "4. 在服务器上执行："
echo "   cd /root"
echo "   mkdir -p startup-graveyard"
echo "   cd startup-graveyard"
echo "   tar -xzf /tmp/startup-graveyard.tar.gz"
echo "   bash scripts/docker-deploy.sh"
echo ""
echo "或者直接使用Docker Compose："
echo "   docker compose build"
echo "   docker compose up -d"
echo ""
